# Generated by Django 4.2.4 on 2023-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_sensor_id_alter_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
